version: 2

sources:
  - name: src
    database: sourcedb
    description: This is the source database
    schema: mk_mall
    tables:
      - name: nations
        columns:
          - name: n_nationkey
            tests:
              - unique
              - not_null
      - name: regions
        columns:
          - name: r_regionkey
            tests:
              - unique
              - not_null
      - name: orders
        config:
          freshness:
            warn_after: {count: 20, period: day}
            error_after: {count: 30, period: day}
        loaded_at_field: o_orderdate::timestamp
      - name: customers
      - name: lineitems

